language: sml
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes smlnj mlton ml-yacc ml-ulex
install:
  - git submodule init
  - git submodule update --init --recursive
script:
  - ./script/test.sh
  - cat "build-smlnj.log"
  - cat "build-mlton.log"

notifications:
  email: false

deploy:
  provider: releases
  api_key: ${api_key}
  file: "bin/redprl"
  skip_cleanup: true
  on:
    tags: true
